version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: Password4DEV

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8050:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password4DEV

db.general_paper_collection.find({}, {normalized_title:1}).sort({_id:1}).forEach(function(doc){
    db.general_paper_collection.remove({_id:{$gt:doc._id}, normalized_title:doc.normalized_title});
})